blank_issues_enabled: true
contact_links:
  - name: ğŸ¥ Video Playlist
    url: https://www.youtube.com/
    about: View the examples on YouTube
  - name: #ï¸âƒ£ Slack Us
    url:
    about: Join the Slack workspace to learn more!
